_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest50_detectron-255b5649.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
  ROI_HEADS:
    NUM_CLASSES: 7
#    SCORE_THRESH_TEST: 0.1
#    NMS_THRESH_TEST: 0.1
  RETINANET:
    NUM_CLASSES: 7
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.001
  STEPS: (30000, 40000)
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
DATASETS:
  TRAIN: ("bulb_wise_tl_train",)
  TEST: ("bulb_wise_tl_train",)
OUTPUT_DIR: "output/bulb-tl-schedule"
