_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "https://hangzh.s3-us-west-1.amazonaws.com/encoding/models/resnest50_detectron-255b5649.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    RADIX: 2
    NORM: "SyncBN"
  FPN:
    NORM: "SyncBN"
SOLVER:
  IMS_PER_BATCH: 24
  STEPS: (10500, 14000)
  MAX_ITER: 17500
  CHECKPOINT_PERIOD: 700
TEST:
  EVAL_PERIOD: 700
DATASETS:
  TRAIN: ("bulb_wise_tl_train",)
  TEST: ("bulb_wise_tl_train",)
OUTPUT_DIR: "output/bulb-tl-schedule"
